[package]
name = "mal-rust"
version = "0.1.0"
authors = ["Tyler Goodwin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "step0_repl"
path = "src/bin/step0_repl.rs"